#!/usr/bin/env python3
"""
Generate RMG_en.ts — English reference translation file.

This file is the "source of truth" for translators:
  - Every translatable string used by RMG (across the RMG, RMG-Input,
    and RMG-Audio targets) appears here.
  - The <translation> body is identical to the <source> body —
    English is the source language of the codebase, so the "translation"
    IS the source text.
  - No type="unfinished" markers, so lrelease will compile every entry
    into the .qm and the language will appear in the Settings dialog.

How translators use this file:
  1. Pick a new locale code (e.g. "uk" for Ukrainian).
  2. Copy RMG_en.ts to RMG_<locale>.ts.
  3. Change language="en" to language="<locale>" on the <TS> tag.
  4. For each <message>, replace the <translation> body with the
     translated string (or leave it as the English source if you
     want to ship that entry as-is temporarily).
  5. Drop the new file into Source/RMG/Translations/.
  6. Re-run CMake — the new language appears in Settings automatically.

This file is regenerated by running:
    python3 Source/RMG/Translations/generate_en_ts.py > Source/RMG/Translations/RMG_en.ts

The extraction logic is identical to generate_ru_ts.py:
  - .ui files: context = <class> value, strings = all <string> element text
  - .cpp files: context = C++ class name (or filename stem), strings = tr("...")
"""

import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import defaultdict
from xml.sax.saxutils import escape as xml_escape


def extract_ui_strings(ui_path):
    """Extract (context, [strings]) from a .ui file."""
    tree = ET.parse(ui_path)
    root = tree.getroot()

    class_elem = root.find("class")
    if class_elem is None or not class_elem.text:
        return None, []

    context = class_elem.text.strip()

    strings = []
    for string_elem in root.iter("string"):
        # Use itertext to capture all text content (including HTML child
        # elements). Join, then strip whitespace.
        parts = list(string_elem.itertext())
        text = "".join(parts).strip()
        if text:
            strings.append(text)

    return context, strings


def extract_cpp_tr_strings(cpp_path):
    """Extract tr("...") calls from a C++ file."""
    text = Path(cpp_path).read_text(encoding="utf-8", errors="replace")

    # Determine the C++ class name for the context.
    # If the file declares `class Foo :`, use Foo. Otherwise fall back
    # to the filename stem (e.g. MainWindow.cpp -> MainWindow).
    class_name = Path(cpp_path).stem
    m = re.search(r'^class\s+(\w+)\s*:', text, re.MULTILINE)
    if m:
        class_name = m.group(1)

    results = []
    # Match tr("...") or tr("...", "...") — only captures the first
    # argument (the source string). Handles escaped quotes inside the
    # string literal. Does NOT handle multi-line string concatenation,
    # which doesn't appear in this codebase.
    pattern = r'\btr\s*\(\s*"((?:[^"\\]|\\.)*)"\s*[,)]'
    for m in re.finditer(pattern, text):
        raw = m.group(1)
        # Unescape C++ string escapes: \" -> ", \\ -> \, \n -> newline, etc.
        s = raw.replace('\\"', '"').replace('\\n', '\n').replace('\\t', '\t').replace('\\\\', '\\')
        results.append((class_name, s))

    return results


def main():
    # repo_root = Source/  (parent of parent of parent of parent of this script)
    # script:    Source/RMG/Translations/generate_en_ts.py
    # parent^1:  Translations
    # parent^2:  RMG
    # parent^3:  Source
    repo_root = Path(__file__).resolve().parent.parent.parent.parent

    scan_dirs = [
        repo_root / "Source" / "RMG",
        repo_root / "Source" / "RMG-Input",
        repo_root / "Source" / "RMG-Audio",
    ]

    # context -> set of source strings (deduplicated)
    all_strings = defaultdict(set)

    for scan_dir in scan_dirs:
        if not scan_dir.exists():
            continue
        for ui_file in scan_dir.rglob("*.ui"):
            context, strings = extract_ui_strings(ui_file)
            if context:
                for s in strings:
                    all_strings[context].add(s)
        for cpp_file in scan_dir.rglob("*.cpp"):
            pairs = extract_cpp_tr_strings(cpp_file)
            for ctx, s in pairs:
                all_strings[ctx].add(s)

    # Generate the .ts XML.
    lines = []
    lines.append('<?xml version="1.0" encoding="utf-8"?>')
    lines.append('<!DOCTYPE TS>')
    lines.append('<!--')
    lines.append('  RMG English reference translation.')
    lines.append('  Generated by generate_en_ts.py from source code extraction.')
    lines.append('')
    lines.append('  This file is the SOURCE OF TRUTH for translators:')
    lines.append('    - Every translatable string used by RMG appears here.')
    lines.append('    - The <translation> body is identical to <source>, because')
    lines.append('      English is the source language of the codebase.')
    lines.append('    - No type="unfinished" markers, so lrelease compiles every')
    lines.append('      entry into the .qm and the language appears in Settings.')
    lines.append('')
    lines.append('  To add a new language:')
    lines.append('    1. Copy this file to RMG_<locale>.ts')
    lines.append('    2. Change language="en" to language="<locale>" on <TS>')
    lines.append('    3. Replace each <translation> body with your translation')
    lines.append('    4. Drop the file into Source/RMG/Translations/')
    lines.append('    5. Re-run CMake — the new language appears in Settings.')
    lines.append('')
    lines.append('  To refresh source strings after editing .ui/.cpp files:')
    lines.append('      lupdate Source/RMG Source/RMG-Input Source/RMG-Audio -ts Source/RMG/Translations/RMG_en.ts')
    lines.append('  Then merge any new entries into your other .ts files via:')
    lines.append('      lconvert -i RMG_en.ts RMG_<locale>.ts -o RMG_<locale>.ts')
    lines.append('-->')
    lines.append('<TS version="2.1" language="en">')

    total_messages = 0
    for context in sorted(all_strings.keys()):
        lines.append('    <context>')
        lines.append(f'        <name>{xml_escape(context)}</name>')
        for source in sorted(all_strings[context]):
            lines.append('        <message>')
            lines.append(f'            <source>{xml_escape(source)}</source>')
            # English "translation" = the source text itself.
            # No type="unfinished" attribute — we want every entry
            # compiled into the .qm so the language is selectable
            # and shows real strings when the user picks English.
            lines.append(f'            <translation>{xml_escape(source)}</translation>')
            lines.append('        </message>')
            total_messages += 1
        lines.append('    </context>')

    lines.append('</TS>')

    output = "\n".join(lines) + "\n"
    sys.stdout.write(output)

    # Stats to stderr (doesn't pollute the .ts file)
    print(f"\n# Generated {total_messages} messages in {len(all_strings)} contexts", file=sys.stderr)


if __name__ == "__main__":
    main()
