<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<!--
  RMG Russian translation.
  Generated by generate_ru_ts.py from source code extraction.

  To refresh after changing source strings:
      lupdate Source/RMG Source/RMG-Input Source/RMG-Audio -ts Source/RMG/Translations/RMG_ru.ts
  Then edit in Qt Linguist to fill in any new unfinished entries.
-->
<TS version="2.1" language="ru_RU">
    <context>
        <name>AboutDialog</name>
        <message>
            <source>&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name="qrichtext" content="1" /&gt;&lt;meta charset="utf-8" /&gt;&lt;style type="text/css"&gt;
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;"&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;span style=" font-weight:700;"&gt;Rosalie's Mupen GUI &lt;/span&gt;is an easy to use &amp;amp; cross-platform mupen64plus front-end written in C++ &amp;amp; Qt.&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Version: {version}&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;License: GPLv3&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Contributors:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Rosalie Wanders (&lt;a href="https://github.com/Rosalie241"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Rosalie241&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- GhostlyDark (&lt;a href="https://github.com/GhostlyDark"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/GhostlyDark&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- JakobDev (&lt;a href="https://github.com/JakobDev"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/JakobDev&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- JaxonWasTaken (&lt;a href="https://github.com/JaxonWasTaken"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/JaxonWasTaken&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RetraCarteR (&lt;a href="https://github.com/RetraCarteR"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/RetraCarteR&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- orbea (&lt;a href="https://github.com/orbea"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/orbea&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Fanatic-64 (&lt;a href="https://github.com/Fanatic-64"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Fanatic-64&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Alice (&lt;a href="https://github.com/nekopsykose"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/nekopsykose&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Cosima Neidahl (&lt;a href="https://github.com/OPNA2608"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/OPNA2608&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- kev4cards (&lt;a href="https://github.com/kev4cards"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/kev4cards&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Logan McNaughton (&lt;a href="https://github.com/loganmc10"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/loganmc10&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- porcino (&lt;a href="https://github.com/porcino"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/porcino&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Sebastian Grabowski (&lt;a href="https://github.com/picsel2"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/picsel2&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Alejandro Bringas Martinez (&lt;a href="https://github.com/iWeaker"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/iWeaker&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Samuel (&lt;a href="https://github.com/Samueru-sama"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Samueru-sama&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- cursedUs64-git (&lt;a href="https://github.com/cursedUs64-git"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/cursedUs64-git&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Pcgaming575 (&lt;a href="https://github.com/Pcgaming575"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Pcgaming575&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Jaffacakelover (&lt;a href="https://github.com/Jaffacakelover"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Jaffacakelover&lt;/span&gt;&lt;/a&gt;) &lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RibShark (&lt;a href="https://github.com/RibShark"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/RibShark&lt;/span&gt;&lt;/a&gt;) &lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Special thanks:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Gent (&lt;a href="https://github.com/TheGent"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/TheGent&lt;/span&gt;&lt;/a&gt;) for providing custom cheats&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Jaffacakelover (&lt;a href="https://github.com/Jaffacakelover"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Jaffacakelover&lt;/span&gt;&lt;/a&gt;) for making the controller image for RMG-Input&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;It uses the following third party projects:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Qt6 (&lt;a href="https://www.qt.io/product/qt6"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://www.qt.io/product/qt6&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- SDL3 (&lt;a href="https://github.com/libsdl-org/SDL"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/libsdl-org/SDL&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- imgui (&lt;a href="https://github.com/ocornut/imgui"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/ocornut/imgui&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- lzma (&lt;a href="https://7-zip.org/sdk.html"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://7-zip.org/sdk.html&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- vosk-api (&lt;a href="https://github.com/alphacep/vosk-api"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/alphacep/vosk-api&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RemixIcon (&lt;a href="https://github.com/Remix-Design/RemixIcon"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Remix-Design/RemixIcon&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;It includes the following third party projects:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-core (&lt;a href="https://github.com/mupen64plus/mupen64plus-core"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-core&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-input-gca (&lt;a href="https://github.com/amatho/mupen64plus-input-gca"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/amatho/mupen64plus-input-gca&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-input-raphnetraw (&lt;a href="https://github.com/raphnet/mupen64plus-input-raphnetraw"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/raphnet/mupen64plus-input-raphnetraw&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-cxd4 (&lt;a href="https://github.com/mupen64plus/mupen64plus-rsp-cxd4"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-rsp-cxd4&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-hle (&lt;a href="https://github.com/mupen64plus/mupen64plus-rsp-hle)"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-rsp-hle&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-parallel (&lt;a href="https://github.com/libretro/parallel-rsp"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/libretro/parallel-rsp&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-angrylion-plus (&lt;a href="https://github.com/ata4/angrylion-rdp-plus"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/ata4/angrylion-rdp-plus&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-GLideN64 (&lt;a href="https://github.com/gonetz/GLideN64"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/gonetz/GLideN64&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-parallel (&lt;a href="https://github.com/Themaister/parallel-rdp-standalone"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Themaister/parallel-rdp-standalone&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- SDL_GameControllerDB (&lt;a href="https://github.com/mdqinc/SDL_GameControllerDB"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mdqinc/SDL_GameControllerDB&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
            <translation type="unfinished">&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name="qrichtext" content="1" /&gt;&lt;meta charset="utf-8" /&gt;&lt;style type="text/css"&gt;
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;"&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;span style=" font-weight:700;"&gt;Rosalie's Mupen GUI &lt;/span&gt;is an easy to use &amp;amp; cross-platform mupen64plus front-end written in C++ &amp;amp; Qt.&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Version: {version}&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;License: GPLv3&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Contributors:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Rosalie Wanders (&lt;a href="https://github.com/Rosalie241"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Rosalie241&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- GhostlyDark (&lt;a href="https://github.com/GhostlyDark"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/GhostlyDark&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- JakobDev (&lt;a href="https://github.com/JakobDev"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/JakobDev&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- JaxonWasTaken (&lt;a href="https://github.com/JaxonWasTaken"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/JaxonWasTaken&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RetraCarteR (&lt;a href="https://github.com/RetraCarteR"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/RetraCarteR&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- orbea (&lt;a href="https://github.com/orbea"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/orbea&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Fanatic-64 (&lt;a href="https://github.com/Fanatic-64"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Fanatic-64&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Alice (&lt;a href="https://github.com/nekopsykose"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/nekopsykose&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Cosima Neidahl (&lt;a href="https://github.com/OPNA2608"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/OPNA2608&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- kev4cards (&lt;a href="https://github.com/kev4cards"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/kev4cards&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Logan McNaughton (&lt;a href="https://github.com/loganmc10"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/loganmc10&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- porcino (&lt;a href="https://github.com/porcino"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/porcino&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Sebastian Grabowski (&lt;a href="https://github.com/picsel2"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/picsel2&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Alejandro Bringas Martinez (&lt;a href="https://github.com/iWeaker"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/iWeaker&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Samuel (&lt;a href="https://github.com/Samueru-sama"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Samueru-sama&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- cursedUs64-git (&lt;a href="https://github.com/cursedUs64-git"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/cursedUs64-git&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Pcgaming575 (&lt;a href="https://github.com/Pcgaming575"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Pcgaming575&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Jaffacakelover (&lt;a href="https://github.com/Jaffacakelover"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Jaffacakelover&lt;/span&gt;&lt;/a&gt;) &lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RibShark (&lt;a href="https://github.com/RibShark"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/RibShark&lt;/span&gt;&lt;/a&gt;) &lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;Special thanks:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Gent (&lt;a href="https://github.com/TheGent"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/TheGent&lt;/span&gt;&lt;/a&gt;) for providing custom cheats&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Jaffacakelover (&lt;a href="https://github.com/Jaffacakelover"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Jaffacakelover&lt;/span&gt;&lt;/a&gt;) for making the controller image for RMG-Input&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;It uses the following third party projects:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- Qt6 (&lt;a href="https://www.qt.io/product/qt6"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://www.qt.io/product/qt6&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- SDL3 (&lt;a href="https://github.com/libsdl-org/SDL"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/libsdl-org/SDL&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- imgui (&lt;a href="https://github.com/ocornut/imgui"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/ocornut/imgui&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- lzma (&lt;a href="https://7-zip.org/sdk.html"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://7-zip.org/sdk.html&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- vosk-api (&lt;a href="https://github.com/alphacep/vosk-api"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/alphacep/vosk-api&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- RemixIcon (&lt;a href="https://github.com/Remix-Design/RemixIcon"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Remix-Design/RemixIcon&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;It includes the following third party projects:&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-core (&lt;a href="https://github.com/mupen64plus/mupen64plus-core"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-core&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-input-gca (&lt;a href="https://github.com/amatho/mupen64plus-input-gca"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/amatho/mupen64plus-input-gca&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-input-raphnetraw (&lt;a href="https://github.com/raphnet/mupen64plus-input-raphnetraw"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/raphnet/mupen64plus-input-raphnetraw&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-cxd4 (&lt;a href="https://github.com/mupen64plus/mupen64plus-rsp-cxd4"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-rsp-cxd4&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-hle (&lt;a href="https://github.com/mupen64plus/mupen64plus-rsp-hle)"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mupen64plus/mupen64plus-rsp-hle&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-rsp-parallel (&lt;a href="https://github.com/libretro/parallel-rsp"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/libretro/parallel-rsp&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-angrylion-plus (&lt;a href="https://github.com/ata4/angrylion-rdp-plus"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/ata4/angrylion-rdp-plus&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-GLideN64 (&lt;a href="https://github.com/gonetz/GLideN64"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/gonetz/GLideN64&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- mupen64plus-video-parallel (&lt;a href="https://github.com/Themaister/parallel-rdp-standalone"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/Themaister/parallel-rdp-standalone&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;
&lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;- SDL_GameControllerDB (&lt;a href="https://github.com/mdqinc/SDL_GameControllerDB"&gt;&lt;span style=" text-decoration: underline; color:#1d99f3;"&gt;https://github.com/mdqinc/SDL_GameControllerDB&lt;/span&gt;&lt;/a&gt;)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
        </message>
        <message>
            <source>About RMG</source>
            <translation>О программе RMG</translation>
        </message>
    </context>
    <context>
        <name>AddCheatDialog</name>
        <message>
            <source>&lt;address&gt; &lt;value&gt;</source>
            <translation>&lt;адрес&gt; &lt;значение&gt;</translation>
        </message>
        <message>
            <source>&lt;value&gt; &lt;label&gt;</source>
            <translation>&lt;значение&gt; &lt;метка&gt;</translation>
        </message>
        <message>
            <source>Add Cheat</source>
            <translation>Добавить чит</translation>
        </message>
        <message>
            <source>Author</source>
            <translation>Автор</translation>
        </message>
        <message>
            <source>Code:</source>
            <translation>Код:</translation>
        </message>
        <message>
            <source>Name</source>
            <translation>Название</translation>
        </message>
        <message>
            <source>Notes:</source>
            <translation>Заметки:</translation>
        </message>
        <message>
            <source>Options:</source>
            <translation>Опции:</translation>
        </message>
    </context>
    <context>
        <name>CheatsDialog</name>
        <message>
            <source>Add</source>
            <translation>Добавить</translation>
        </message>
        <message>
            <source>Cheats</source>
            <translation>Чит-коды</translation>
        </message>
        <message>
            <source>Edit</source>
            <translation>Изменить</translation>
        </message>
        <message>
            <source>Notes</source>
            <translation>Заметки</translation>
        </message>
        <message>
            <source>Remove</source>
            <translation>Удалить</translation>
        </message>
    </context>
    <context>
        <name>ChooseCheatOptionDialog</name>
        <message>
            <source>Cheat Options</source>
            <translation>Опции чита</translation>
        </message>
        <message>
            <source>Choose Cheat Option</source>
            <translation>Выбрать опцию чита</translation>
        </message>
    </context>
    <context>
        <name>ControllerWidget</name>
        <message>
            <source>+</source>
            <translation>+</translation>
        </message>
        <message>
            <source>-</source>
            <translation>-</translation>
        </message>
        <message>
            <source>A:</source>
            <translation>A:</translation>
        </message>
        <message>
            <source>Add</source>
            <translation>Добавить</translation>
        </message>
        <message>
            <source>Analog Stick</source>
            <translation>Аналоговый стик</translation>
        </message>
        <message>
            <source>Analog Stick Sensitivity: </source>
            <translation>Чувствительность аналогового стика: </translation>
        </message>
        <message>
            <source>Analog Stick Sensitivity: 100%</source>
            <translation>Чувствительность аналогового стика: 100%</translation>
        </message>
        <message>
            <source>Auto-Configure</source>
            <translation>Автонастройка</translation>
        </message>
        <message>
            <source>B:</source>
            <translation>B:</translation>
        </message>
        <message>
            <source>C-Buttons</source>
            <translation>Кнопки C</translation>
        </message>
        <message>
            <source>ControllerWidget</source>
            <translation>Виджет контроллера</translation>
        </message>
        <message>
            <source>Deadzone: 25%</source>
            <translation>Мёртвая зона: 25%</translation>
        </message>
        <message>
            <source>Digital Pad</source>
            <translation>Цифровой крест</translation>
        </message>
        <message>
            <source>Down:</source>
            <translation>Вниз:</translation>
        </message>
        <message>
            <source>Hotkeys</source>
            <translation>Горячие клавиши</translation>
        </message>
        <message>
            <source>Input Device</source>
            <translation>Устройство ввода</translation>
        </message>
        <message>
            <source>L-Shoulder:</source>
            <translation>Лево-плечо:</translation>
        </message>
        <message>
            <source>Left:</source>
            <translation>Влево:</translation>
        </message>
        <message>
            <source>Options</source>
            <translation>Опции</translation>
        </message>
        <message>
            <source>Profile</source>
            <translation>Профиль</translation>
        </message>
        <message>
            <source>R-Shoulder:</source>
            <translation>Право-плечо:</translation>
        </message>
        <message>
            <source>Refresh</source>
            <translation>Обновить</translation>
        </message>
        <message>
            <source>Remove</source>
            <translation>Удалить</translation>
        </message>
        <message>
            <source>Reset</source>
            <translation>Сброс</translation>
        </message>
        <message>
            <source>Right:</source>
            <translation>Вправо:</translation>
        </message>
        <message>
            <source>Start:</source>
            <translation>Старт:</translation>
        </message>
        <message>
            <source>Up:</source>
            <translation>Вверх:</translation>
        </message>
        <message>
            <source>Z-Trigger:</source>
            <translation>Z-триггер:</translation>
        </message>
    </context>
    <context>
        <name>CreateNetplaySessionDialog</name>
        <message>
            <source>Create Netplay Session</source>
            <translation>Создать сессию сетевой игры</translation>
        </message>
        <message>
            <source>Nickname</source>
            <translation>Никнейм</translation>
        </message>
        <message>
            <source>Password</source>
            <translation>Пароль</translation>
        </message>
        <message>
            <source>Server</source>
            <translation>Сервер</translation>
        </message>
        <message>
            <source>Server ping</source>
            <translation>Пинг сервера</translation>
        </message>
        <message>
            <source>Session name</source>
            <translation>Название сессии</translation>
        </message>
    </context>
    <context>
        <name>CreateNetplaySessionEmptyWidget</name>
        <message>
            <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;No ROMs were found.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;You can configure the ROM browser directory or refresh the ROM browser.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
            <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;ROM не найдены.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Вы можете настроить каталог ROM или обновить браузер ROM.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
        </message>
        <message>
            <source>Form</source>
            <translation>Форма</translation>
        </message>
    </context>
    <context>
        <name>DownloadUpdateDialog</name>
        <message>
            <source>Downloading ...</source>
            <translation>Загрузка...</translation>
        </message>
        <message>
            <source>Downloading Update</source>
            <translation>Загрузка обновления</translation>
        </message>
    </context>
    <context>
        <name>HotkeysDialog</name>
        <message>
            <source>100%</source>
            <translation>100%</translation>
        </message>
        <message>
            <source>125%</source>
            <translation>125%</translation>
        </message>
        <message>
            <source>150%</source>
            <translation>150%</translation>
        </message>
        <message>
            <source>175%</source>
            <translation>175%</translation>
        </message>
        <message>
            <source>200%</source>
            <translation>200%</translation>
        </message>
        <message>
            <source>225%</source>
            <translation>225%</translation>
        </message>
        <message>
            <source>25%</source>
            <translation>25%</translation>
        </message>
        <message>
            <source>250%</source>
            <translation>250%</translation>
        </message>
        <message>
            <source>275%</source>
            <translation>275%</translation>
        </message>
        <message>
            <source>300%</source>
            <translation>300%</translation>
        </message>
        <message>
            <source>50%</source>
            <translation>50%</translation>
        </message>
        <message>
            <source>75%</source>
            <translation>75%</translation>
        </message>
        <message>
            <source>Capture Screenshot</source>
            <translation>Сделать снимок экрана</translation>
        </message>
        <message>
            <source>Controller Pak</source>
            <translation>Контроллер Pak</translation>
        </message>
        <message>
            <source>Current Save State</source>
            <translation>Текущий слот сохранения</translation>
        </message>
        <message>
            <source>Decrease Slot</source>
            <translation>Предыдущий слот</translation>
        </message>
        <message>
            <source>Exit</source>
            <translation>Выход</translation>
        </message>
        <message>
            <source>Full Screen</source>
            <translation>Полный экран</translation>
        </message>
        <message>
            <source>GS Button</source>
            <translation>Кнопка GameShark</translation>
        </message>
        <message>
            <source>Hard Reset</source>
            <translation>Жёсткий сброс</translation>
        </message>
        <message>
            <source>Hotkeys</source>
            <translation>Горячие клавиши</translation>
        </message>
        <message>
            <source>Increase Slot</source>
            <translation>Следующий слот</translation>
        </message>
        <message>
            <source>Limit FPS</source>
            <translation>Ограничить FPS</translation>
        </message>
        <message>
            <source>Load State</source>
            <translation>Загрузить состояние</translation>
        </message>
        <message>
            <source>Pause</source>
            <translation>Пауза</translation>
        </message>
        <message>
            <source>Remove pak</source>
            <translation>Извлечь Pak</translation>
        </message>
        <message>
            <source>Save State</source>
            <translation>Сохранить состояние</translation>
        </message>
        <message>
            <source>Shutdown</source>
            <translation>Остановить</translation>
        </message>
        <message>
            <source>Slot 0</source>
            <translation>Слот 0</translation>
        </message>
        <message>
            <source>Slot 1</source>
            <translation>Слот 1</translation>
        </message>
        <message>
            <source>Slot 2</source>
            <translation>Слот 2</translation>
        </message>
        <message>
            <source>Slot 3</source>
            <translation>Слот 3</translation>
        </message>
        <message>
            <source>Slot 4</source>
            <translation>Слот 4</translation>
        </message>
        <message>
            <source>Slot 5</source>
            <translation>Слот 5</translation>
        </message>
        <message>
            <source>Slot 6</source>
            <translation>Слот 6</translation>
        </message>
        <message>
            <source>Slot 7</source>
            <translation>Слот 7</translation>
        </message>
        <message>
            <source>Slot 8</source>
            <translation>Слот 8</translation>
        </message>
        <message>
            <source>Slot 9</source>
            <translation>Слот 9</translation>
        </message>
        <message>
            <source>Soft Reset</source>
            <translation>Мягкий сброс</translation>
        </message>
        <message>
            <source>Speed Factor</source>
            <translation>Скорость</translation>
        </message>
        <message>
            <source>Switch to memory pak</source>
            <translation>Переключить на Memory Pak</translation>
        </message>
        <message>
            <source>Switch to rumble pak</source>
            <translation>Переключить на Rumble Pak</translation>
        </message>
        <message>
            <source>System</source>
            <translation>Система</translation>
        </message>
        <message>
            <source>These hotkeys are only for controllers</source>
            <translation>Эти горячие клавиши только для контроллеров</translation>
        </message>
        <message>
            <source>View</source>
            <translation>Вид</translation>
        </message>
    </context>
    <context>
        <name>InstallUpdateDialog</name>
        <message>
            <source>Installing Update</source>
            <translation>Установка обновления</translation>
        </message>
        <message>
            <source>Installing...</source>
            <translation>Установка...</translation>
        </message>
    </context>
    <context>
        <name>LogDialog</name>
        <message>
            <source>Log</source>
            <translation>Журнал</translation>
        </message>
    </context>
    <context>
        <name>MainDialog</name>
        <message>
            <source>Advanced</source>
            <translation>Дополнительно</translation>
        </message>
        <message>
            <source>Changes will be applied on next emulation run</source>
            <translation>Изменения вступят в силу при следующем запуске эмуляции</translation>
        </message>
        <message>
            <source>Default frequency</source>
            <translation>Базовая частота</translation>
        </message>
        <message>
            <source>Mute</source>
            <translation>Без звука</translation>
        </message>
        <message>
            <source>Player 1</source>
            <translation>Игрок 1</translation>
        </message>
        <message>
            <source>Player 2</source>
            <translation>Игрок 2</translation>
        </message>
        <message>
            <source>Player 3</source>
            <translation>Игрок 3</translation>
        </message>
        <message>
            <source>Player 4</source>
            <translation>Игрок 4</translation>
        </message>
        <message>
            <source>Resampler</source>
            <translation>Передискретизатор</translation>
        </message>
        <message>
            <source>Rosalie's Mupen GUI - Audio Plugin</source>
            <translation>Rosalie's Mupen GUI — звуковой плагин</translation>
        </message>
        <message>
            <source>Rosalie's Mupen GUI - Input Plugin</source>
            <translation>Rosalie's Mupen GUI — плагин ввода</translation>
        </message>
        <message>
            <source>Swap left and right channel</source>
            <translation>Поменять местами левый и правый каналы</translation>
        </message>
        <message>
            <source>TextLabel</source>
            <translation>Текстовая метка</translation>
        </message>
        <message>
            <source>Volume</source>
            <translation>Громкость</translation>
        </message>
        <message>
            <source>speex-fixed-0</source>
            <translation>speex-fixed-0</translation>
        </message>
        <message>
            <source>speex-fixed-1</source>
            <translation>speex-fixed-1</translation>
        </message>
        <message>
            <source>speex-fixed-10</source>
            <translation>speex-fixed-10</translation>
        </message>
        <message>
            <source>speex-fixed-2</source>
            <translation>speex-fixed-2</translation>
        </message>
        <message>
            <source>speex-fixed-3</source>
            <translation>speex-fixed-3</translation>
        </message>
        <message>
            <source>speex-fixed-4</source>
            <translation>speex-fixed-4</translation>
        </message>
        <message>
            <source>speex-fixed-5</source>
            <translation>speex-fixed-5</translation>
        </message>
        <message>
            <source>speex-fixed-6</source>
            <translation>speex-fixed-6</translation>
        </message>
        <message>
            <source>speex-fixed-7</source>
            <translation>speex-fixed-7</translation>
        </message>
        <message>
            <source>speex-fixed-8</source>
            <translation>speex-fixed-8</translation>
        </message>
        <message>
            <source>speex-fixed-9</source>
            <translation>speex-fixed-9</translation>
        </message>
        <message>
            <source>src-linear</source>
            <translation>src-linear</translation>
        </message>
        <message>
            <source>src-sinc-best-quality</source>
            <translation>src-sinc-best-quality</translation>
        </message>
        <message>
            <source>src-sinc-fastest</source>
            <translation>src-sinc-fastest</translation>
        </message>
        <message>
            <source>src-sinc-medium-quality</source>
            <translation>src-sinc-medium-quality</translation>
        </message>
        <message>
            <source>src-zero-order-hold</source>
            <translation>src-zero-order-hold</translation>
        </message>
        <message>
            <source>trivial</source>
            <translation>trivial</translation>
        </message>
    </context>
    <context>
        <name>MainWindow</name>
        <message>
            <source>&amp;100%</source>
            <translation>&amp;100%</translation>
        </message>
        <message>
            <source>&amp;25%</source>
            <translation>&amp;25%</translation>
        </message>
        <message>
            <source>&amp;300%</source>
            <translation>&amp;300%</translation>
        </message>
        <message>
            <source>&amp;50%</source>
            <translation>&amp;50%</translation>
        </message>
        <message>
            <source>&amp;75%</source>
            <translation>&amp;75%</translation>
        </message>
        <message>
            <source>&amp;About RMG</source>
            <translation>&amp;О RMG</translation>
        </message>
        <message>
            <source>&amp;Audio</source>
            <translation>&amp;Звук</translation>
        </message>
        <message>
            <source>&amp;Check For Updates</source>
            <translation>&amp;Проверить обновления</translation>
        </message>
        <message>
            <source>&amp;Clear ROM Cache</source>
            <translation>О&amp;чистить кэш ROM</translation>
        </message>
        <message>
            <source>&amp;Create Session</source>
            <translation>&amp;Создать сессию</translation>
        </message>
        <message>
            <source>&amp;Current Save State</source>
            <translation>&amp;Текущий слот сохранения</translation>
        </message>
        <message>
            <source>&amp;Exit</source>
            <translation>В&amp;ыход</translation>
        </message>
        <message>
            <source>&amp;Fullscreen</source>
            <translation>Во &amp;весь экран</translation>
        </message>
        <message>
            <source>&amp;GS Button</source>
            <translation>Кнопка &amp;GameShark</translation>
        </message>
        <message>
            <source>&amp;Game List</source>
            <translation>Список &amp;игр</translation>
        </message>
        <message>
            <source>&amp;Github Repository</source>
            <translation>Репозиторий &amp;GitHub</translation>
        </message>
        <message>
            <source>&amp;Graphics</source>
            <translation>&amp;Графика</translation>
        </message>
        <message>
            <source>&amp;Hard Reset</source>
            <translation>&amp;Жёсткий сброс</translation>
        </message>
        <message>
            <source>&amp;Input</source>
            <translation>&amp;Ввод</translation>
        </message>
        <message>
            <source>&amp;Limit FPS</source>
            <translation>&amp;Ограничить FPS</translation>
        </message>
        <message>
            <source>&amp;Log</source>
            <translation>&amp;Журнал</translation>
        </message>
        <message>
            <source>&amp;Pause</source>
            <translation>&amp;Пауза</translation>
        </message>
        <message>
            <source>&amp;RSP</source>
            <translation>&amp;RSP</translation>
        </message>
        <message>
            <source>&amp;Refresh ROMs</source>
            <translation>&amp;Обновить список ROM</translation>
        </message>
        <message>
            <source>&amp;Reset</source>
            <translation>&amp;Сброс</translation>
        </message>
        <message>
            <source>&amp;Settings</source>
            <translation>&amp;Настройки</translation>
        </message>
        <message>
            <source>&amp;Slot 0</source>
            <translation>Слот &amp;0</translation>
        </message>
        <message>
            <source>&amp;Soft Reset</source>
            <translation>&amp;Мягкий сброс</translation>
        </message>
        <message>
            <source>&amp;Start ROM</source>
            <translation>&amp;Запустить ROM</translation>
        </message>
        <message>
            <source>&amp;Status Bar</source>
            <translation>Строка &amp;состояния</translation>
        </message>
        <message>
            <source>&amp;Toolbar</source>
            <translation>&amp;Панель инструментов</translation>
        </message>
        <message>
            <source>&amp;Uniform Size (Grid View)</source>
            <translation>&amp;Одинаковый размер (сетка)</translation>
        </message>
        <message>
            <source>125%</source>
            <translation>125%</translation>
        </message>
        <message>
            <source>150%</source>
            <translation>150%</translation>
        </message>
        <message>
            <source>175%</source>
            <translation>175%</translation>
        </message>
        <message>
            <source>2&amp;00%</source>
            <translation>2&amp;00%</translation>
        </message>
        <message>
            <source>225%</source>
            <translation>225%</translation>
        </message>
        <message>
            <source>250%</source>
            <translation>250%</translation>
        </message>
        <message>
            <source>275%</source>
            <translation>275%</translation>
        </message>
        <message>
            <source>Browse Sessions</source>
            <translation>Просмотр сессий</translation>
        </message>
        <message>
            <source>Cheats...</source>
            <translation>Чит-коды...</translation>
        </message>
        <message>
            <source>Ga&amp;me Grid</source>
            <translation>Сетка &amp;игр</translation>
        </message>
        <message>
            <source>He&amp;lp</source>
            <translation>Спр&amp;авка</translation>
        </message>
        <message>
            <source>L&amp;oad State</source>
            <translation>З&amp;агрузить состояние</translation>
        </message>
        <message>
            <source>Loa&amp;d...</source>
            <translation>Загрузит&amp;ь...</translation>
        </message>
        <message>
            <source>Netplay</source>
            <translation>Сетевая игра</translation>
        </message>
        <message>
            <source>Open 64DD Disk</source>
            <translation>Открыть 64DD диск</translation>
        </message>
        <message>
            <source>Open N64 ROM</source>
            <translation>Открыть N64 ROM</translation>
        </message>
        <message>
            <source>Open N64 ROM or 64DD Disk</source>
            <translation>Открыть N64 ROM или 64DD диск</translation>
        </message>
        <message>
            <source>Open Save State</source>
            <translation>Открыть сохранение состояния</translation>
        </message>
        <message>
            <source>Rosalie's Mupen GUI (VERSION)</source>
            <translation>Rosalie's Mupen GUI (VERSION)</translation>
        </message>
        <message>
            <source>S&amp;hutdown</source>
            <translation>О&amp;становить</translation>
        </message>
        <message>
            <source>S&amp;ystem</source>
            <translation>С&amp;истема</translation>
        </message>
        <message>
            <source>Sa&amp;ve State</source>
            <translation>Со&amp;хранить состояние</translation>
        </message>
        <message>
            <source>Save As...</source>
            <translation>Сохранить как...</translation>
        </message>
        <message>
            <source>Save State</source>
            <translation>Сохранить состояние</translation>
        </message>
        <message>
            <source>Save State (*.dat *.state *.st* *.pj*);;All Files (*)</source>
            <translation>Сохранения (*.dat *.state *.st* *.pj*);;Все файлы (*)</translation>
        </message>
        <message>
            <source>Save State (*.state);;Project64 Save State (*.pj);;All Files (*)</source>
            <translation>Сохранение состояния (*.state);;Project64 (*.pj);;Все файлы (*)</translation>
        </message>
        <message>
            <source>Scree&amp;nshot</source>
            <translation>С&amp;нимок экрана</translation>
        </message>
        <message>
            <source>Search</source>
            <translation>Поиск</translation>
        </message>
        <message>
            <source>Select ROM Directory</source>
            <translation>Выбрать каталог ROM</translation>
        </message>
        <message>
            <source>Setti&amp;ngs</source>
            <translation>Настр&amp;ойки</translation>
        </message>
        <message>
            <source>Slot &amp;1</source>
            <translation>Слот &amp;1</translation>
        </message>
        <message>
            <source>Slot &amp;2</source>
            <translation>Слот &amp;2</translation>
        </message>
        <message>
            <source>Slot &amp;3</source>
            <translation>Слот &amp;3</translation>
        </message>
        <message>
            <source>Slot &amp;4</source>
            <translation>Слот &amp;4</translation>
        </message>
        <message>
            <source>Slot &amp;5</source>
            <translation>Слот &amp;5</translation>
        </message>
        <message>
            <source>Slot &amp;6</source>
            <translation>Слот &amp;6</translation>
        </message>
        <message>
            <source>Slot &amp;7</source>
            <translation>Слот &amp;7</translation>
        </message>
        <message>
            <source>Slot &amp;8</source>
            <translation>Слот &amp;8</translation>
        </message>
        <message>
            <source>Slot &amp;9</source>
            <translation>Слот &amp;9</translation>
        </message>
        <message>
            <source>Speed &amp;Factor</source>
            <translation>Скорость &amp;воспроизведения</translation>
        </message>
        <message>
            <source>Start Co&amp;mbo</source>
            <translation>Запустить ко&amp;мбо</translation>
        </message>
        <message>
            <source>View</source>
            <translation>Вид</translation>
        </message>
        <message>
            <source>View Session</source>
            <translation>Открыть сессию</translation>
        </message>
        <message>
            <source>toolBar</source>
            <translation>Панель инструментов</translation>
        </message>
    </context>
    <context>
        <name>NetplaySessionBrowserDialog</name>
        <message>
            <source>Netplay Session Browser</source>
            <translation>Браузер сессий сетевой игры</translation>
        </message>
        <message>
            <source>Nickname</source>
            <translation>Никнейм</translation>
        </message>
        <message>
            <source>Server</source>
            <translation>Сервер</translation>
        </message>
        <message>
            <source>Server ping</source>
            <translation>Пинг сервера</translation>
        </message>
    </context>
    <context>
        <name>NetplaySessionBrowserEmptyWidget</name>
        <message>
            <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;No sessions were found.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;You can create your own session or refresh the session list.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
            <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;Сессии не найдены.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Вы можете создать свою сессию или обновить список сессий.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
        </message>
        <message>
            <source>Form</source>
            <translation>Форма</translation>
        </message>
    </context>
    <context>
        <name>NetplaySessionDialog</name>
        <message>
            <source>1</source>
            <translation>1</translation>
        </message>
        <message>
            <source>Chat</source>
            <translation>Чат</translation>
        </message>
        <message>
            <source>Cheats</source>
            <translation>Чит-коды</translation>
        </message>
        <message>
            <source>Game name</source>
            <translation>Название игры</translation>
        </message>
        <message>
            <source>Netplay Session</source>
            <translation>Сессия сетевой игры</translation>
        </message>
        <message>
            <source>Players</source>
            <translation>Игроки</translation>
        </message>
        <message>
            <source>Send</source>
            <translation>Отправить</translation>
        </message>
        <message>
            <source>Session name</source>
            <translation>Название сессии</translation>
        </message>
    </context>
    <context>
        <name>NetplaySessionPasswordDialog</name>
        <message>
            <source>Enter Password</source>
            <translation>Введите пароль</translation>
        </message>
        <message>
            <source>Password:</source>
            <translation>Пароль:</translation>
        </message>
    </context>
    <context>
        <name>OptionsDialog</name>
        <message>
            <source>Advanced</source>
            <translation>Дополнительно</translation>
        </message>
        <message>
            <source>Automatic</source>
            <translation>Автоматически</translation>
        </message>
        <message>
            <source>Change</source>
            <translation>Изменить</translation>
        </message>
        <message>
            <source>Changes will be applied on next emulation run</source>
            <translation>Изменения вступят в силу при следующем запуске эмуляции</translation>
        </message>
        <message>
            <source>Controller</source>
            <translation>Контроллер</translation>
        </message>
        <message>
            <source>Controller Pak</source>
            <translation>Контроллер Pak</translation>
        </message>
        <message>
            <source>Filter events based on joystick type for axis</source>
            <translation>Фильтровать события по типу джойстика для осей</translation>
        </message>
        <message>
            <source>Filter events based on joystick type for buttons</source>
            <translation>Фильтровать события по типу джойстика для кнопок</translation>
        </message>
        <message>
            <source>Gameboy ROM</source>
            <translation>ROM Gameboy</translation>
        </message>
        <message>
            <source>Gameboy save</source>
            <translation>Сохранение Gameboy</translation>
        </message>
        <message>
            <source>Gamepad</source>
            <translation>Геймпад</translation>
        </message>
        <message>
            <source>Joystick</source>
            <translation>Джойстик</translation>
        </message>
        <message>
            <source>Memory</source>
            <translation>Память</translation>
        </message>
        <message>
            <source>None</source>
            <translation>Нет</translation>
        </message>
        <message>
            <source>Open Gameboy ROM</source>
            <translation>Открыть ROM Gameboy</translation>
        </message>
        <message>
            <source>Open Gameboy Save</source>
            <translation>Открыть сохранение Gameboy</translation>
        </message>
        <message>
            <source>Options</source>
            <translation>Опции</translation>
        </message>
        <message>
            <source>Remove duplicate mappings</source>
            <translation>Удалять дубликаты назначений</translation>
        </message>
        <message>
            <source>Rumble</source>
            <translation>Вибрация</translation>
        </message>
        <message>
            <source>SDL controller mode</source>
            <translation>Режим SDL-контроллера</translation>
        </message>
        <message>
            <source>Test Rumble</source>
            <translation>Тест вибрации</translation>
        </message>
        <message>
            <source>Transfer</source>
            <translation>Переносной</translation>
        </message>
        <message>
            <source>Transfer Pak</source>
            <translation>Transfer Pak</translation>
        </message>
        <message>
            <source>User Interface</source>
            <translation>Пользовательский интерфейс</translation>
        </message>
    </context>
    <context>
        <name>RomBrowserEmptyWidget</name>
        <message>
            <source>.n64/.z64/.v64 (N64 Roms)</source>
            <translation>.n64/.z64/.v64 (ROM N64)</translation>
        </message>
        <message>
            <source>.ndd/.d64 (64DD Disks)</source>
            <translation>.ndd/.d64 (диски 64DD)</translation>
        </message>
        <message>
            <source>.zip/.7z (Archive)</source>
            <translation>.zip/.7z (архив)</translation>
        </message>
        <message>
            <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;No ROMs in supported formats were found.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Please select a directory with ROMs to begin.&lt;/p&gt;&lt;p&gt;ROMs in the following formats will be scanned and listed: &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
            <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=" font-weight:700;"&gt;Не найдено ROM в поддерживаемых форматах.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Выберите каталог с ROM для начала работы.&lt;/p&gt;&lt;p&gt;Будут просканированы и показаны ROM в следующих форматах: &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
        </message>
        <message>
            <source>Form</source>
            <translation>Форма</translation>
        </message>
        <message>
            <source>Refresh</source>
            <translation>Обновить</translation>
        </message>
        <message>
            <source>Select ROM Directory...</source>
            <translation>Выбрать каталог ROM...</translation>
        </message>
    </context>
    <context>
        <name>RomBrowserWidget</name>
        <message>
            <source>Cover Image (*.png *.jpeg *.jpg)</source>
            <translation>Обложка (*.png *.jpeg *.jpg)</translation>
        </message>
        <message>
            <source>Open Cover Image</source>
            <translation>Открыть обложку</translation>
        </message>
    </context>
    <context>
        <name>RomInfoDialog</name>
        <message>
            <source>CRC1</source>
            <translation>CRC1</translation>
        </message>
        <message>
            <source>CRC2</source>
            <translation>CRC2</translation>
        </message>
        <message>
            <source>File Name</source>
            <translation>Имя файла</translation>
        </message>
        <message>
            <source>Game I.D.</source>
            <translation>ID игры</translation>
        </message>
        <message>
            <source>Game Region</source>
            <translation>Регион игры</translation>
        </message>
        <message>
            <source>Game Type</source>
            <translation>Тип игры</translation>
        </message>
        <message>
            <source>Location</source>
            <translation>Расположение</translation>
        </message>
        <message>
            <source>MD5</source>
            <translation>MD5</translation>
        </message>
        <message>
            <source>Name</source>
            <translation>Название</translation>
        </message>
        <message>
            <source>ROM Information</source>
            <translation>Информация о ROM</translation>
        </message>
        <message>
            <source>System Region</source>
            <translation>Регион системы</translation>
        </message>
    </context>
    <context>
        <name>SettingsDialog</name>
        <message>
            <source>&amp;Use PIF ROM</source>
            <translation>&amp;Использовать PIF ROM</translation>
        </message>
        <message>
            <source>1</source>
            <translation>1</translation>
        </message>
        <message>
            <source>100%</source>
            <translation>100%</translation>
        </message>
        <message>
            <source>125%</source>
            <translation>125%</translation>
        </message>
        <message>
            <source>150%</source>
            <translation>150%</translation>
        </message>
        <message>
            <source>16 KB EEPROM</source>
            <translation>16 КБ EEPROM</translation>
        </message>
        <message>
            <source>175%</source>
            <translation>175%</translation>
        </message>
        <message>
            <source>2</source>
            <translation>2</translation>
        </message>
        <message>
            <source>200%</source>
            <translation>200%</translation>
        </message>
        <message>
            <source>225%</source>
            <translation>225%</translation>
        </message>
        <message>
            <source>25%</source>
            <translation>25%</translation>
        </message>
        <message>
            <source>250%</source>
            <translation>250%</translation>
        </message>
        <message>
            <source>275%</source>
            <translation>275%</translation>
        </message>
        <message>
            <source>3</source>
            <translation>3</translation>
        </message>
        <message>
            <source>300%</source>
            <translation>300%</translation>
        </message>
        <message>
            <source>4</source>
            <translation>4</translation>
        </message>
        <message>
            <source>4 KB EEPROM</source>
            <translation>4 КБ EEPROM</translation>
        </message>
        <message>
            <source>4 MB</source>
            <translation>4 МБ</translation>
        </message>
        <message>
            <source>5</source>
            <translation>5</translation>
        </message>
        <message>
            <source>50%</source>
            <translation>50%</translation>
        </message>
        <message>
            <source>6</source>
            <translation>6</translation>
        </message>
        <message>
            <source>64DD</source>
            <translation>64DD</translation>
        </message>
        <message>
            <source>75%</source>
            <translation>75%</translation>
        </message>
        <message>
            <source>8 MB</source>
            <translation>8 МБ</translation>
        </message>
        <message>
            <source>American Retail 64DD IPL ROM</source>
            <translation>Американский розничный 64DD IPL ROM</translation>
        </message>
        <message>
            <source>Ask for confirmation during drag and drop</source>
            <translation>Запрашивать подтверждение при перетаскивании</translation>
        </message>
        <message>
            <source>Ask for confirmation on exit</source>
            <translation>Запрашивать подтверждение при выходе</translation>
        </message>
        <message>
            <source>Audio</source>
            <translation>Звук</translation>
        </message>
        <message>
            <source>Audio Plugin</source>
            <translation>Плагин звука</translation>
        </message>
        <message>
            <source>Automatic</source>
            <translation>Автоматически</translation>
        </message>
        <message>
            <source>Automatically switch to fullscreen on emulation start</source>
            <translation>Автоматически переходить в полный экран при запуске эмуляции</translation>
        </message>
        <message>
            <source>Background color</source>
            <translation>Цвет фона</translation>
        </message>
        <message>
            <source>Black</source>
            <translation>Чёрная</translation>
        </message>
        <message>
            <source>Bottom Left</source>
            <translation>Снизу слева</translation>
        </message>
        <message>
            <source>Bottom Right</source>
            <translation>Снизу справа</translation>
        </message>
        <message>
            <source>CPU Emulator</source>
            <translation>Эмулятор ЦП</translation>
        </message>
        <message>
            <source>CPU emulator</source>
            <translation>Эмулятор ЦП</translation>
        </message>
        <message>
            <source>Cached Interpreter</source>
            <translation>Кэширующий интерпретатор</translation>
        </message>
        <message>
            <source>Capture Screenshot</source>
            <translation>Сделать снимок экрана</translation>
        </message>
        <message>
            <source>Change</source>
            <translation>Изменить</translation>
        </message>
        <message>
            <source>Changes will be applied on next application run</source>
            <translation>Изменения вступят в силу при следующем запуске приложения</translation>
        </message>
        <message>
            <source>Changes will be applied on next emulation run</source>
            <translation>Изменения вступят в силу при следующем запуске эмуляции</translation>
        </message>
        <message>
            <source>Cheats</source>
            <translation>Чит-коды</translation>
        </message>
        <message>
            <source>Check for updates</source>
            <translation>Проверять обновления</translation>
        </message>
        <message>
            <source>Controller pak</source>
            <translation>Контроллер Pak</translation>
        </message>
        <message>
            <source>Core</source>
            <translation>Ядро</translation>
        </message>
        <message>
            <source>Counter Factor</source>
            <translation>Коэффициент счётчика</translation>
        </message>
        <message>
            <source>Current Save State</source>
            <translation>Текущий слот сохранения</translation>
        </message>
        <message>
            <source>Decrease Volume</source>
            <translation>Уменьшить громкость</translation>
        </message>
        <message>
            <source>Development 64DD IPL ROM</source>
            <translation>Разработческий 64DD IPL ROM</translation>
        </message>
        <message>
            <source>Directories</source>
            <translation>Каталоги</translation>
        </message>
        <message>
            <source>Disk save type</source>
            <translation>Тип сохранения диска</translation>
        </message>
        <message>
            <source>Duration</source>
            <translation>Длительность</translation>
        </message>
        <message>
            <source>Dynamic Recompiler</source>
            <translation>Динамический рекомпилятор</translation>
        </message>
        <message>
            <source>Emulation</source>
            <translation>Эмуляция</translation>
        </message>
        <message>
            <source>Enable On-Screen Display</source>
            <translation>Включить экранное уведомление (OSD)</translation>
        </message>
        <message>
            <source>Exit</source>
            <translation>Выход</translation>
        </message>
        <message>
            <source>Flash RAM</source>
            <translation>Flash RAM</translation>
        </message>
        <message>
            <source>Full Disk Copy</source>
            <translation>Полная копия диска</translation>
        </message>
        <message>
            <source>Full Screen</source>
            <translation>Полный экран</translation>
        </message>
        <message>
            <source>Fusion</source>
            <translation>Fusion</translation>
        </message>
        <message>
            <source>Fusion Dark</source>
            <translation>Fusion (тёмная)</translation>
        </message>
        <message>
            <source>GS Button</source>
            <translation>Кнопка GameShark</translation>
        </message>
        <message>
            <source>Game</source>
            <translation>Игра</translation>
        </message>
        <message>
            <source>General</source>
            <translation>Общие</translation>
        </message>
        <message>
            <source>Good Name</source>
            <translation>Корректное имя</translation>
        </message>
        <message>
            <source>Graphics</source>
            <translation>Графика</translation>
        </message>
        <message>
            <source>Hard Reset</source>
            <translation>Жёсткий сброс</translation>
        </message>
        <message>
            <source>Hide cursor during emulation</source>
            <translation>Скрывать курсор во время эмуляции</translation>
        </message>
        <message>
            <source>Hide cursor during fullscreen emulation</source>
            <translation>Скрывать курсор при полноэкранной эмуляции</translation>
        </message>
        <message>
            <source>Horizontal padding</source>
            <translation>Горизонтальный отступ</translation>
        </message>
        <message>
            <source>Hotkeys</source>
            <translation>Горячие клавиши</translation>
        </message>
        <message>
            <source>Icon theme</source>
            <translation>Тема значков</translation>
        </message>
        <message>
            <source>Increase Volume</source>
            <translation>Увеличить громкость</translation>
        </message>
        <message>
            <source>Input</source>
            <translation>Ввод</translation>
        </message>
        <message>
            <source>Input Plugin</source>
            <translation>Плагин ввода</translation>
        </message>
        <message>
            <source>Interface</source>
            <translation>Интерфейс</translation>
        </message>
        <message>
            <source>Internal ROM Name</source>
            <translation>Внутреннее имя ROM</translation>
        </message>
        <message>
            <source>Japanese Retail 64DD IPL ROM</source>
            <translation>Японский розничный 64DD IPL ROM</translation>
        </message>
        <message>
            <source>Language</source>
            <translation>Язык</translation>
        </message>
        <message>
            <source>Limit FPS</source>
            <translation>Ограничить FPS</translation>
        </message>
        <message>
            <source>Load</source>
            <translation>Загрузить</translation>
        </message>
        <message>
            <source>Load State</source>
            <translation>Загрузить состояние</translation>
        </message>
        <message>
            <source>Location</source>
            <translation>Расположение</translation>
        </message>
        <message>
            <source>Log</source>
            <translation>Журнал</translation>
        </message>
        <message>
            <source>Make sure to use a LLE RSP plugin (e.g. paraLLEl RSP) when using a LLE Video plugin (e.g. paraLLEl)</source>
            <translation>При использовании LLE-плагина видео (например paraLLEl) убедитесь, что выбран LLE-плагин RSP (например paraLLEl RSP)</translation>
        </message>
        <message>
            <source>Memory Size</source>
            <translation>Размер памяти</translation>
        </message>
        <message>
            <source>NTSC PIF ROM</source>
            <translation>PIF ROM (NTSC)</translation>
        </message>
        <message>
            <source>Native</source>
            <translation>Системная</translation>
        </message>
        <message>
            <source>Netplay</source>
            <translation>Сетевая игра</translation>
        </message>
        <message>
            <source>Nickname</source>
            <translation>Никнейм</translation>
        </message>
        <message>
            <source>No</source>
            <translation>Нет</translation>
        </message>
        <message>
            <source>None</source>
            <translation>Нет</translation>
        </message>
        <message>
            <source>OSD</source>
            <translation>OSD (экранные уведомления)</translation>
        </message>
        <message>
            <source>Open American Retail 64DD IPL</source>
            <translation>Открыть американский розничный 64DD IPL</translation>
        </message>
        <message>
            <source>Open Japanese Development 64DD IPL</source>
            <translation>Открыть японский разработческий 64DD IPL</translation>
        </message>
        <message>
            <source>Open Japanese Retail 64DD IPL</source>
            <translation>Открыть японский розничный 64DD IPL</translation>
        </message>
        <message>
            <source>Open NTSC PIF ROM</source>
            <translation>Открыть PIF ROM (NTSC)</translation>
        </message>
        <message>
            <source>Open PAL PIF ROM</source>
            <translation>Открыть PIF ROM (PAL)</translation>
        </message>
        <message>
            <source>OpenGL</source>
            <translation>OpenGL</translation>
        </message>
        <message>
            <source>OpenGL ES</source>
            <translation>OpenGL ES</translation>
        </message>
        <message>
            <source>OpenGL type</source>
            <translation>Тип OpenGL</translation>
        </message>
        <message>
            <source>Overclocking Factor</source>
            <translation>Коэффициент разгона</translation>
        </message>
        <message>
            <source>Override core settings</source>
            <translation>Переопределять настройки ядра</translation>
        </message>
        <message>
            <source>Override game specific settings</source>
            <translation>Переопределять настройки игры</translation>
        </message>
        <message>
            <source>PAL PIF ROM</source>
            <translation>PIF ROM (PAL)</translation>
        </message>
        <message>
            <source>Pause</source>
            <translation>Пауза</translation>
        </message>
        <message>
            <source>Pause emulation on focus loss</source>
            <translation>Пауза эмуляции при потере фокуса</translation>
        </message>
        <message>
            <source>Plugins</source>
            <translation>Плагины</translation>
        </message>
        <message>
            <source>Pure Interpreter</source>
            <translation>Чистый интерпретатор</translation>
        </message>
        <message>
            <source>RAM Area Only</source>
            <translation>Только область RAM</translation>
        </message>
        <message>
            <source>ROM Browser</source>
            <translation>Браузер ROM</translation>
        </message>
        <message>
            <source>ROM search limit</source>
            <translation>Максимум ROM при поиске</translation>
        </message>
        <message>
            <source>RSP</source>
            <translation>RSP</translation>
        </message>
        <message>
            <source>Randomize PI/SI Interrupt Timing</source>
            <translation>Случайные интервалы прерываний PI/SI</translation>
        </message>
        <message>
            <source>Randomize PI/SI interrupt timing</source>
            <translation>Случайные интервалы прерываний PI/SI</translation>
        </message>
        <message>
            <source>Reality Signal Processor Plugin</source>
            <translation>Плагин RSP (Reality Signal Processor)</translation>
        </message>
        <message>
            <source>Refresh ROM List</source>
            <translation>Обновить список ROM</translation>
        </message>
        <message>
            <source>Remove duplicate keybindings</source>
            <translation>Удалять дубликаты назначений клавиш</translation>
        </message>
        <message>
            <source>Resume emulation on focus gain</source>
            <translation>Продолжать эмуляцию при возврате фокуса</translation>
        </message>
        <message>
            <source>SDL3</source>
            <translation>SDL3</translation>
        </message>
        <message>
            <source>SI DMA Duration</source>
            <translation>Длительность SI DMA</translation>
        </message>
        <message>
            <source>SRAM</source>
            <translation>SRAM</translation>
        </message>
        <message>
            <source>Save (SRAM) Directory</source>
            <translation>Каталог сохранений (SRAM)</translation>
        </message>
        <message>
            <source>Save (State) Directory</source>
            <translation>Каталог сохранений (State)</translation>
        </message>
        <message>
            <source>Save As</source>
            <translation>Сохранить как</translation>
        </message>
        <message>
            <source>Save State</source>
            <translation>Сохранить состояние</translation>
        </message>
        <message>
            <source>Save Type</source>
            <translation>Тип сохранения</translation>
        </message>
        <message>
            <source>Save filename format</source>
            <translation>Формат имени файла сохранения</translation>
        </message>
        <message>
            <source>Screenshot Directory</source>
            <translation>Каталог скриншотов</translation>
        </message>
        <message>
            <source>Search</source>
            <translation>Поиск</translation>
        </message>
        <message>
            <source>Search sub-directories</source>
            <translation>Искать в подкаталогах</translation>
        </message>
        <message>
            <source>Select Save (SRAM) Directory</source>
            <translation>Выбрать каталог сохранений (SRAM)</translation>
        </message>
        <message>
            <source>Select Save (State) Directory</source>
            <translation>Выбрать каталог сохранений (State)</translation>
        </message>
        <message>
            <source>Select Screenshot Directory</source>
            <translation>Выбрать каталог скриншотов</translation>
        </message>
        <message>
            <source>Select the interface language. Choose "System Default" to use the operating system locale. Changes will be applied on next application run.</source>
            <translation>Выберите язык интерфейса. Выберите «По умолчанию (системный)», чтобы использовать язык операционной системы. Изменения вступят в силу при следующем запуске приложения.</translation>
        </message>
        <message>
            <source>Server list URL</source>
            <translation>URL списка серверов</translation>
        </message>
        <message>
            <source>Settings</source>
            <translation>Настройки</translation>
        </message>
        <message>
            <source>Show verbose messages</source>
            <translation>Показывать подробные сообщения</translation>
        </message>
        <message>
            <source>Shutdown</source>
            <translation>Остановить</translation>
        </message>
        <message>
            <source>Slot 0</source>
            <translation>Слот 0</translation>
        </message>
        <message>
            <source>Slot 1</source>
            <translation>Слот 1</translation>
        </message>
        <message>
            <source>Slot 2</source>
            <translation>Слот 2</translation>
        </message>
        <message>
            <source>Slot 3</source>
            <translation>Слот 3</translation>
        </message>
        <message>
            <source>Slot 4</source>
            <translation>Слот 4</translation>
        </message>
        <message>
            <source>Slot 5</source>
            <translation>Слот 5</translation>
        </message>
        <message>
            <source>Slot 6</source>
            <translation>Слот 6</translation>
        </message>
        <message>
            <source>Slot 7</source>
            <translation>Слот 7</translation>
        </message>
        <message>
            <source>Slot 8</source>
            <translation>Слот 8</translation>
        </message>
        <message>
            <source>Slot 9</source>
            <translation>Слот 9</translation>
        </message>
        <message>
            <source>Soft Reset</source>
            <translation>Мягкий сброс</translation>
        </message>
        <message>
            <source>Speed Factor</source>
            <translation>Скорость</translation>
        </message>
        <message>
            <source>Start Combo</source>
            <translation>Запустить комбо</translation>
        </message>
        <message>
            <source>Start ROM</source>
            <translation>Запустить ROM</translation>
        </message>
        <message>
            <source>Statusbar message duration</source>
            <translation>Длительность сообщений в строке состояния</translation>
        </message>
        <message>
            <source>System</source>
            <translation>Система</translation>
        </message>
        <message>
            <source>System Default</source>
            <translation>По умолчанию (системный)</translation>
        </message>
        <message>
            <source>Text color</source>
            <translation>Цвет текста</translation>
        </message>
        <message>
            <source>The On-Screen Display will only work with OpenGL video plugins</source>
            <translation>Экранные уведомления (OSD) работают только с OpenGL-плагинами видео</translation>
        </message>
        <message>
            <source>Theme</source>
            <translation>Тема</translation>
        </message>
        <message>
            <source>Toggle Mute Volume</source>
            <translation>Включить/выключить звук</translation>
        </message>
        <message>
            <source>Top Left</source>
            <translation>Сверху слева</translation>
        </message>
        <message>
            <source>Top Right</source>
            <translation>Сверху справа</translation>
        </message>
        <message>
            <source>Transfer Pak</source>
            <translation>Transfer Pak</translation>
        </message>
        <message>
            <source>Vertical padding</source>
            <translation>Вертикальный отступ</translation>
        </message>
        <message>
            <source>Video Plugin</source>
            <translation>Плагин видео</translation>
        </message>
        <message>
            <source>Video capture backend</source>
            <translation>Бэкенд захвата видео</translation>
        </message>
        <message>
            <source>View</source>
            <translation>Вид</translation>
        </message>
        <message>
            <source>White</source>
            <translation>Белая</translation>
        </message>
        <message>
            <source>Yes</source>
            <translation>Да</translation>
        </message>
        <message>
            <source>px</source>
            <translation>пикс</translation>
        </message>
        <message>
            <source>seconds</source>
            <translation>секунд</translation>
        </message>
    </context>
    <context>
        <name>UpdateDialog</name>
        <message>
            <source>A new version is available</source>
            <translation>Доступна новая версия</translation>
        </message>
        <message>
            <source>Don't check for updates again</source>
            <translation>Больше не проверять обновления</translation>
        </message>
        <message>
            <source>v0.2.2 Available</source>
            <translation>v0.2.2 доступна</translation>
        </message>
    </context>
</TS>
